// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TimeCyclePlugin","status":true,"description":"76시간 66분 12초 주기를 계산하여 게임 상단에 남은 시간을 표시하는 플러그인입니다.","parameters":{}}
];
